### ISSUE TITLE
'startOffset' is undefined when svg namespace used

### ISSUE THREAD

**Issue by bondib** [MeirionHughes/aurelia-template-lint#117]
TypeError: Cannot read property 'startOffset' of undefined

TypeError: Cannot read property 'startOffset' of undefined
    at ...//node_modules/template-lint/dist/ast.js:30:49
    at Array.map (native)
    at Parser.<anonymous> (...//node_modules/template-lint/dist/ast.js:26:32)
    at emitMany (events.js:126:20)
    at Parser.emit (events.js:195:7)
    at Parser.SAXParser._handleToken (...//node_modules/parse5/lib/sax/index.js:171:14)
    at Parser.SAXParser._runParsingLoop (...//node_modules/parse5/lib/sax/index.js:149:18)
    at Parser.SAXParser._transform (...//node_modules/parse5/lib/sax/index.js:76:14)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Parser.Writable.write (_stream_writable.js:214:11)
    at Readable.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Readable.emit (events.js:182:7)
    at Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:751:26)
    at emitReadable_ (_stream_readable.js:420:3)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by MeirionHughes** [comment]
Can you rimraf your node_modules and make sure you're on 0.9.8. If it still happens, could you post the html that causes it to die?

**Comment by bondib** [comment]
Hi.
So yes - i'm using 0.9.8.

I debugged it and found the issue (I think). It's with the following html:

  <svg if.bind="!userContext.imageUri" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40" style="width:20px;height:20px;">
                                    <circle cx="20" cy="20" r="18" stroke="grey" stroke-width="1" fill="#FFFFFF" />
                                    <text x="50%" y="50%" text-anchor="middle" stroke="#51c5cf" stroke-width="2px" dy=".3em" letter-spacing="2">${userContext.caps}</text>
                                </svg>


It fails on xmlns as attrLoc is undefined with this attribute - as a previous check is strangely incorrect (x.prefix !== undefined) which makes the attribute name become ":xmlns" instead of just "xmlns"...

**Comment by bondib** [comment]
The html:

`  <svg if.bind="!userContext.imageUri" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40" style="width:20px;height:20px;">
                                    <circle cx="20" cy="20" r="18" stroke="grey" stroke-width="1" fill="#FFFFFF" />
                                    <text x="50%" y="50%" text-anchor="middle" stroke="#51c5cf" stroke-width="2px" dy=".3em" letter-spacing="2">${userContext.caps}</text>
                                </svg>`

**Comment by MeirionHughes** [comment]
ahh yeh, its because parse5 changed how it deals with attribute names and namespaces. I'll sort this when I get home.

**Comment by bondib** [comment]
Great, thanks!

I have another one for you... Will open a different issue... :-)

**Comment by MeirionHughes** [comment]
published as `aurelia-template-lint 0.9.9`. Also require `template-lint 0.8.9`
