### ISSUE TITLE
TypeError: _aureliaPal.DOM.createElement is not a function

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#45]
@MeirionHughes, i guess this error is related to Your effort with pal-nodejs. Could You provide instructions how to take an advantage of all the cool stuff You've implemented recently?

Currently when I do:
`npm install gulp-aurelia-template-lint@0.7.2 --save-dev`
then I get following error:

```cmd
[21:02:12] 'lint-templates' errored after 19 ms
[21:02:12] Error: Error invoking SVGAnalyzer. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: _aureliaPal.DOM.createElement is not a function
Inner Error Stack:
TypeError: _aureliaPal.DOM.createElement is not a function
    at createElement (C:\path\to\proj\node_modules\aurelia-template-lint\node_modules\aurelia-templating-binding\node_modules\aurelia-binding\dist\commonjs\aurelia-binding.js:4418:29)
    at new SVGAnalyzer (C:\path\to\proj\node_modules\aurelia-template-lint\node_modules\aurelia-templating-binding\node_modules\aurelia-binding\dist\commonjs\aurelia-binding.js:4427:9)
    at Object.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:347:12)
    at InvocationHandler.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at Object.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:377:103)
    at InvocationHandler.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at Object.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:371:55)
    at InvocationHandler.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at new StaticTypeRule (C:\path\to\proj\node_modules\aurelia-template-lint\dist\rules\static-type.js:20:47)
    at new AureliaLinter (C:\path\to\proj\node_modules\aurelia-template-lint\dist\aurelia-linter.js:37:13)
    at module.exports.stream._transform (C:\path\to\proj\node_modules\gulp-aurelia-template-lint\index.js:16:18)
    at Gulp.<anonymous> (C:\path\to\proj\gulp\tasks\lint-templates.js:17:15)
    at module.exports (C:\path\to\proj\node_modules\orchestrator\lib\runTask.js:34:7)
End Inner Error Stack
------------------------------------------------

    at new AggregateError (C:\path\to\proj\node_modules\aurelia-dependency-injection\node_modules\aurelia-pal\dist\commonjs\aurelia-pal.js:36:11)
    at Container.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:590:13)
    at StrategyResolver.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at Object.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:377:103)
    at InvocationHandler.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at Object.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:371:55)
    at InvocationHandler.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (C:\path\to\proj\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at new StaticTypeRule (C:\path\to\proj\node_modules\aurelia-template-lint\dist\rules\static-type.js:20:47)
    at new AureliaLinter (C:\path\to\proj\node_modules\aurelia-template-lint\dist\aurelia-linter.js:37:13)
    at module.exports.stream._transform (C:\path\to\proj\node_modules\gulp-aurelia-template-lint\index.js:16:18)
    at Gulp.<anonymous> (C:\path\to\proj\gulp\tasks\lint-templates.js:17:15)
    at module.exports (C:\path\to\proj\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\path\to\proj\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\path\to\proj\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\path\to\proj\node_modules\orchestrator\index.js:134:8)
```

but when I install gulp-aurelia-template-lint@0.6.0 (aurelia-template-lint@0.6.3), then everything works as it used to :)

**Comment by MeirionHughes** [comment]
I think its related to Aurelia versioning; this is now on the RC since 0.7.3. pal-nodejs also now requires Aurelia RC too. Try npm upgrade?

**Comment by MeirionHughes** [comment]
Also try cloning this repo: 

```
npm install
npm test
node example.js
```

**Comment by atsu85** [comment]
i got it working after updating to aurelia-rc and deleting node_modules and reinstalling all deps :)

**Comment by atsu85** [comment]
As i wrote in my previous comment, I got this issue solved for the project i wanted to lint, but now that I took the advice of @MeirionHughes:
> Also try cloning this repo: 
```cmd
npm install
npm test
node example.js
```

I ran into this issue again - this time some aurelia-template-lint tests fail:
```shell
1) Aurelia Examples encountered a declaration exception
1.1) Error: Error invoking SVGAnalyzer. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: _aureliaPal.DOM.createElement is not a function
Inner Error Stack:
TypeError: _aureliaPal.DOM.createElement is not a function
    at createElement (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-templating-binding\node_modules\aurelia-binding\dist\commonjs\aurelia-binding.js:4418:29)
    at new SVGAnalyzer (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-templating-binding\node_modules\aurelia-binding\dist\commonjs\aurelia-binding.js:4427:9)
    at Object.invoke (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:347:12)
    at InvocationHandler.invoke (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at Object.invoke (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:377:103)
    at InvocationHandler.invoke (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (c:\tmp\proj\cloned\aurelia\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
End Inner Error Stack
------------------------------------------------
```

**Comment by MeirionHughes** [comment]
cannot reproduce; still convinced this is issue mismatch due to aurelia's semver usage. `pal-nodejs` has dependency to `pal` latest. For good measure I've changed your PR to "latest" version. 

I've even updated from node 5 to node 6; still not able to reproduce. 

So congrats we have our first "it works for me!"™

**Comment by atsu85** [comment]
oh, I missed the requirement of node v5 - I had v4.2.4. I'll close it for now and try it out later - I hope I won't get tempted to reopen it again ;)
