### ISSUE TITLE
StaticType Rule bug with throwStaticTypingErrors

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#48]
when I have 
```javascript
var config = new (require('aurelia-template-lint').Config);
config.useStaticTyping = true;
config.sourceFileGlob = "aurelia/src/**/*.ts";
```
the linter works as expected. But after adding 
`config.throwStaticTypingErrors = true;`
then i get an error:

```shell
C:\path\to\proj\node_modules\aurelia-template-lint\dist\rules\static-type.js:44
                        throw error;
                        ^

TypeError: Cannot read property 'kind' of undefined
    at StaticTypeRule.resolveAccessChainToType (C:\path\to\proj\node_modules\aurelia-template-lint\dist\rules\static-type.js:197:39)
    at StaticTypeRule.examineTag (C:\path\to\proj\node_modules\aurelia-template-lint\dist\rules\static-type.js:153:30)
    at Parser.<anonymous> (C:\path\to\proj\node_modules\aurelia-template-lint\dist\rules\static-type.js:40:26)
    at emitMany (events.js:113:20)
    at Parser.emit (events.js:182:7)
    at Parser.SAXParser._handleToken (C:\path\to\proj\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:173:14)
    at Parser.SAXParser._runParsingLoop (C:\path\to\proj\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:151:18)
    at Parser.SAXParser._transform (C:\path\to\proj\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:76:14)
```

that comes from [static-type.ts](https://github.com/MeirionHughes/aurelia-template-lint/blob/81c3bb4a8a5c28a2fa4ada9949a2637b0fcfcfb4/source/rules/static-type.ts#L271):
 `else if (localVar.type.kind !== undefined) {`

**Comment by MeirionHughes** [comment]
yeah that is not a surprise; would be more informative to know what caused it. (looks like something created a local variable and the type wasn't found).

**Comment by atsu85** [comment]
I'd be able to find out more information after [another issue](https://github.com/MeirionHughes/aurelia-template-lint/issues/45#issuecomment-228596763) is solved.

**Comment by MeirionHughes** [comment]
when you're free can you have another try with 0.8 and see if this is still an issue for you.

**Comment by atsu85** [comment]
Thanks. I'm AFTC this weekend, but I'll try to find some time for that next week.

**Comment by atsu85** [comment]
this is fixed by now
