### ISSUE TITLE
Use available aurelia-pal-nodejs

### ISSUE THREAD

**Issue by JeroenVinke** [MeirionHughes/aurelia-template-lint#57]
Got this error after installing and running the linter:

```
Inner Error:
Message: _aureliaPal.DOM.createElement is not a function
Inner Error Stack:
TypeError: _aureliaPal.DOM.createElement is not a function
    at createElement (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-binding\dist\commonjs\aurelia-binding.js:4418:29)
    at new SVGAnalyzer (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-binding\dist\commonjs\aurelia-binding.js:4427:9)
    at Object.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:347:12)
    at InvocationHandler.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at Object.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:377:103)
    at InvocationHandler.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at Object.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:371:55)
    at InvocationHandler.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at SyntaxRule.ASTBuilder (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\dist\ast.js:11:47)
    at SyntaxRule (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\dist\rules\syntax.js:12:14)
    at new AureliaLinter (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\dist\aurelia-linter.js:33:13)
    at module.exports.stream._transform (D:\Development\ERP\ERP\node_modules\gulp-aurelia-template-lint\index.js:16:18)
    at Gulp.<anonymous> (D:\Development\ERP\ERP\gulp\tasks\lint.js:15:15)
End Inner Error Stack
------------------------------------------------

    at new AggregateError (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-pal\dist\commonjs\aurelia-pal.js:36:11)
    at Container.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:590:13)
    at StrategyResolver.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at Object.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:377:103)
    at InvocationHandler.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at Object.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:371:55)
    at InvocationHandler.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:324:166)
    at Container.invoke (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:588:23)
    at StrategyResolver.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:126:35)
    at Container.get (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:519:39)
    at SyntaxRule.ASTBuilder (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\dist\ast.js:11:47)
    at SyntaxRule (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\dist\rules\syntax.js:12:14)
    at new AureliaLinter (D:\Development\ERP\ERP\node_modules\aurelia-template-lint\dist\aurelia-linter.js:33:13)
    at module.exports.stream._transform (D:\Development\ERP\ERP\node_modules\gulp-aurelia-template-lint\index.js:16:18)
    at Gulp.<anonymous> (D:\Development\ERP\ERP\gulp\tasks\lint.js:15:15)
    at module.exports (D:\Development\ERP\ERP\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Development\ERP\ERP\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Development\ERP\ERP\node_modules\orchestrator\index.js:214:10)
```

Looked in my `node_modules/aurelia-template-lint` folder and noticed that even though the dependency is [there](https://github.com/MeirionHughes/aurelia-template-lint/blob/master/package.json#L47) the `aurelia-pal-nodejs` folder was missing. I had to download aurelia-pal-nodejs from [here](https://github.com/MeirionHughes/pal-nodejs/tree/rebase), build it and add the folder to `node_modules/aurelia-template-lint/node_modules/aurelia-pal-nodejs`. After that it worked fine and I was able to resolve a couple of silly mistakes in my HTML :smile: 

Until aurelia-pal-nodejs gets merged into the official repo, it would be useful to point https://github.com/MeirionHughes/aurelia-template-lint/blob/master/package.json#L47 to a correct location (possibly on github). 

Thanks :smile:

**Comment by MeirionHughes** [comment]
Are your other aurelia dependencies up to date on RC version? I think this error pops up if you have an older version of aurelia installed. pal-nodejs requires the RC unfortunately. Others have had the same issue and resolved by a complete wipe of node_modules and reinstall of dependencies. 

Technically its on npm and it does work with a fresh install; the automated builds would be failing otherwise. I did have it installing from github at one point; but it was a pain in the bum to manage while I was still making changes.

**Comment by JeroenVinke** [comment]
Yep, this app is on RC

**Comment by MeirionHughes** [comment]
That's kind of worrying... did you try wiping node_modules and reinstalling?

**Comment by MeirionHughes** [comment]
also are you on node.js 5 / 6 ?

**Comment by JeroenVinke** [comment]
I'm on node 4.4.3, do I need 5/6 ?

**Comment by MeirionHughes** [comment]
I'm not sure, might not be bad idea to update to 5 or 6. I know on 5 when you install something with bad version conflicts, it will tell you the install was erroneous.

**Comment by atsu85** [comment]
@JeroenVinke, I've had some problems with node v4 and aurelia-template-lint v 0.8, but not with node v6

**Comment by MeirionHughes** [comment]
Were able to see if node 5 / 6 fixes the problem?

**Comment by JeroenVinke** [comment]
just checked, and works fine with v6.3.0
